#!/usr/bin/env python3
"""Generate Stage C pointer tables and cascade constants from the unpacked image.

Reads unpacked/ephinea_unpacked_base0x78480000.bin (offset == RVA).
Engine pointers (0x00400000..0x00FFFFFF) are exported as uint32_t VAs.
"""

from __future__ import annotations

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BIN = ROOT / "unpacked" / "ephinea_unpacked_base0x78480000.bin"
OUT_TABLES = ROOT / "src" / "stage_c_tables.h"
OUT_CONST = ROOT / "src" / "cascade_constants.h"

PRIOR_BASE = 0x523BE040  # anchors 0x53146240 → res table @ 0x00D88200

TABLE_SPECS = [
    ("kAnchorW", 0x5318F040, 0x7A),
    ("kAnchorH", 0x5318E6E0, 0x5A),
    ("kAnchorWaddHalf", 0x5318E650, 0x23),
    ("kAnchorWaddFull", 0x5318F2A0, 0x1C),
    ("kAnchorHaddFull", 0x5318E9C8, 0xEB),
    ("kAnchorHaddHalf", 0x5318EF00, 0x0C),
    ("kAspectMultPtr", 0x5318EE3C, 0x0C),
    ("kScaleW", 0x5318F00C, 0x02),
    ("kScaleH", 0x5318EF40, 0x14),
    ("kUshortH", 0x5318E8FC, 0x0C),
    ("kPlayerScale", 0x5318E8D4, 0x05),
]

# Verified by float search in current build (Ghidra _DAT_53176128 drifted)
VERIFIED = {
    "EPH_STOCK_WIDTH": (0x00DB8130, "f32", 640.0),
    "EPH_STOCK_HEIGHT": (0x00DB8128, "f32", 480.0),
    "EPH_ASPECT_4_3": (0x00DB7E94, "f32", 4 / 3),
    "EPH_ONE": (0x00DB7E6C, "f32", 1.0),
    "EPH_HALF": (0x00DB7F34, "f32", 2.0),
    "EPH_HUNDRED": (0x00DB7FC8, "f64", 100.0),
}


def prior_rva(prior_va: int) -> int:
    return prior_va - PRIOR_BASE


def is_engine_va(va: int) -> bool:
    return 0x00400000 <= va <= 0x00FFFFFF


def read_ptr(data: bytes, rva: int) -> int:
    return struct.unpack_from("<I", data, rva)[0]


def emit_tables(data: bytes) -> str:
    lines = [
        "/* Auto-generated by tools/extract_stage_c.py — do not edit. */",
        "#ifndef STAGE_C_TABLES_H",
        "#define STAGE_C_TABLES_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for name, prior, count in TABLE_SPECS:
        base = prior_rva(prior)
        ptrs = [read_ptr(data, base + i * 4) for i in range(count)]
        lines.append(f"/* {name}: {count} slots @ prior 0x{prior:08X}, rva 0x{base:08X} */")
        lines.append(f"#define {name}_COUNT {count}")
        lines.append(f"static const uint32_t {name}[{name}_COUNT] = {{")
        for i, p in enumerate(ptrs):
            suffix = "," if i + 1 < count else ""
            if is_engine_va(p):
                lines.append(f"    0x{p:08X}u{suffix}  /* engine */")
            else:
                lines.append(f"    0x{p:08X}u{suffix}  /* dll/runtime — skip at apply */")
        lines.append("};")
        lines.append("")
    lines.append("#endif /* STAGE_C_TABLES_H */")
    lines.append("")
    return "\n".join(lines)


def emit_constants(data: bytes) -> str:
    lines = [
        "/* Auto-generated by tools/extract_stage_c.py — do not edit. */",
        "#ifndef CASCADE_CONSTANTS_H",
        "#define CASCADE_CONSTANTS_H",
        "",
        "/* Verified stock scalars (current unpacked build) */",
    ]
    for name, (rva, kind, _) in VERIFIED.items():
        if kind == "f32":
            val = struct.unpack_from("<f", data, rva)[0]
            lines.append(f"#define {name} {val:.9g}f")
        else:
            val = struct.unpack_from("<d", data, rva)[0]
            lines.append(f"#define {name} {val:.9g}")
    lines.append("")
    lines.append("/* Stage B aspect ladder (doubles @ prior Ghidra addresses) */")
    bp_prior = [
        0x53175EE8, 0x53175F00, 0x53175F10, 0x53175F18,
        0x53175F30, 0x53175F40, 0x53175F50,
    ]
    lines.append("static const double kAspectBreakpoints[7] = {")
    for i, prior in enumerate(bp_prior):
        rv = prior_rva(prior)
        d = struct.unpack_from("<d", data, rv)[0]
        comma = "," if i < 6 else ""
        lines.append(f"    {d:.17g}{comma}  /* prior 0x{prior:08X} */")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* CASCADE_CONSTANTS_H */")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    data = BIN.read_bytes()
    OUT_TABLES.parent.mkdir(exist_ok=True)
    OUT_TABLES.write_text(emit_tables(data))
    OUT_CONST.write_text(emit_constants(data))
    print(f"Wrote {OUT_TABLES} ({OUT_TABLES.stat().st_size} bytes)")
    print(f"Wrote {OUT_CONST} ({OUT_CONST.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
