#!/usr/bin/env python3
"""Extract registry value-name UTF-16 strings from the unpacked ephinea image."""

from __future__ import annotations

import csv
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BIN = ROOT / "unpacked" / "ephinea_unpacked_base0x78480000.bin"
OUT_H = ROOT / "src" / "registry_strings.h"
OUT_CSV = ROOT / "data" / "registry_strings.csv"

# Decompile-confirmed: prior VA -> {global, clamp notes, string name at current RVA}
REGISTRY_MAP = [
    ("0x5313F208", "HKLM", "KEY_EPHINEA", 0x00D81208, "Software\\\\SonicTeam\\\\PSOBB\\\\Ephinea"),
    ("0x5313FFE4", "HKLM2", "KEY_PSOBB", 0x00D81FE4, "Software\\\\SonicTeam\\\\PSOBB"),
    ("0x5313F24C", "538785a4", "VAL_LOW_PERF", 0x00D818B0, "LOW_PERF"),
    ("0x5313F26C", "5388f9c0", "VAL_RES_HUD", 0x00D8181C, "RES_HUD"),
    ("0x5313F290", "5318e940", "VAL_DGV_PRESENTATION", 0x00D8126C, "DGV_PRESENTATION"),
    ("0x5313F2A4", "5318eed4", "VAL_VSYNC", 0x00D81290, "DGV_VRAM"),  # vsync tied to presentation path
    ("0x5313F2B8", "5318f240", "VAL_FRAME_LIMIT", 0x00D818C4, "CLASSIC_INTRO"),
    ("0x5313F2CC", "5318f028", "VAL_MSAA", 0x00D81324, "MSAA_QUALITY"),
    ("0x5313F2DC", "5318dcfc", "VAL_TEXTURE_FILTER", 0x00D812A4, "USE_BLOOM"),
    ("0x5313F2F4", "53835c5c", "VAL_DISABLE_MIPMAPS", 0x00D8124C, "DISABLE_MIPMAPS"),
    ("0x5313F310", "53870578", "VAL_RENDER_MODE", 0x00D81310, "USE_D3D9"),
    ("0x5313F324", "53a9895c", "VAL_NEW_RES", 0x00D817F8, "NEW_RES"),
    ("0x5313F7BC", "5318d210", "VAL_NEW_RES_WIDTH", 0x00D817BC, "NEW_RES_WIDTH"),
    ("0x5313F7D8", "5318dcdc", "VAL_NEW_RES_HEIGHT", 0x00D817D8, "NEW_RES_HEIGHT"),
    ("0x5313F7F8", "5388f988", "VAL_NEW_RES_IDX", 0x00D817F8, "NEW_RES"),
    ("0x5313F808", "5382fe9c", "VAL_HUD_SCALE", 0x00D81808, "HUD_SCALE"),
    ("0x5313F81C", "53857a5c", "VAL_WIDESCREEN", 0x00D81860, "CLASSIC_FULLSCREEN"),
    ("0x5313F82C", "5388ed90", "VAL_LANG", 0x00D81834, "LANG"),
    ("0x53140048", "match", "STR_MATCH_PSOBB", 0x00D81FE4, "Software\\\\SonicTeam\\\\PSOBB"),
    ("0x53140054", "resource", "STR_RESOURCE", 0x00D802A8, "Ephinea: Phantasy Star Online Blue Burst"),
]


def scan_aligned_strings(data: bytes, start: int, end: int) -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    off = start
    while off < end:
        if off % 2:
            off += 1
            continue
        if off >= 2 and struct.unpack_from("<H", data, off - 2)[0] != 0:
            off += 2
            continue
        chars: list[str] = []
        for i in range(0, 120, 2):
            w = struct.unpack_from("<H", data, off + i)[0]
            if w == 0:
                break
            if w < 32 or w > 0xFFFD:
                chars = []
                break
            chars.append(chr(w))
        if len(chars) >= 3 and all(c.isprintable() for c in chars):
            out.append((off, "".join(chars)))
            off += len(chars) * 2 + 2
        else:
            off += 2
    return out


def main() -> None:
    data = BIN.read_bytes()
    scanned = scan_aligned_strings(data, 0x00D81200, 0x00D82000)

    OUT_CSV.parent.mkdir(exist_ok=True)
    with OUT_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["prior_va", "global", "macro", "string_rva", "string"])
        w.writerows(REGISTRY_MAP)

    lines = [
        "/* Auto-generated by tools/extract_registry.py — wchar literals @ verified RVAs. */",
        "#ifndef REGISTRY_STRINGS_H",
        "#define REGISTRY_STRINGS_H",
        "",
        "#define EPH_REG_STR_RVA(name, rva) ((const wchar_t *)(uintptr_t)(0x78480000u + (rva)))",
        "",
    ]
    for _prior, _global, macro, rva, text in REGISTRY_MAP:
        lines.append(f"#define {macro} L\"{text}\"")
        lines.append(f"#define {macro}_RVA 0x{rva:08X}u")
        lines.append("")

    lines.append("/* All aligned value names in .rdata pool (for lookup) */")
    for rva, text in scanned:
        safe = text.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f"/* 0x{rva:08X} L\"{safe}\" */")
    lines.extend(["", "#endif /* REGISTRY_STRINGS_H */", ""])
    OUT_H.write_text("\n".join(lines))
    print(f"Wrote {OUT_H} and {OUT_CSV}")


if __name__ == "__main__":
    main()
