/* Auto-generated by tools/extract_stage_c.py — do not edit. */
#ifndef CASCADE_CONSTANTS_H
#define CASCADE_CONSTANTS_H

#include <stdint.h>

/* Verified stock scalars (current unpacked build) */
#define EPH_STOCK_WIDTH 640f
#define EPH_STOCK_HEIGHT 480f
#define EPH_ASPECT_4_3 1.33333337f
#define EPH_ONE 1f
#define EPH_HALF 2f
#define EPH_HUNDRED 100

/* Stage B aspect ladder (doubles @ prior Ghidra addresses) */
static const double kAspectBreakpoints[7] = {
    0.22500005352776498,  /* prior 0x53175EE8 */
    0.61111128306947649,  /* prior 0x53175F00 */
    1,  /* prior 0x53175F10 */
    1.01,  /* prior 0x53175F18 */
    1.3,  /* prior 0x53175F30 */
    1.3999999999999999,  /* prior 0x53175F40 */
    1.5  /* prior 0x53175F50 */
};

/* MSVC/Ghidra signed-i32 → f64 bias pair @ prior 0x531761E0 */
#define EPH_I32_TO_F64_POS -0.001562501067382982
#define EPH_I32_TO_F64_NEG 1.5873523201947252e-314

static inline double eph_i32_to_f64(int32_t v)
{
    return (double)v + (v < 0 ? EPH_I32_TO_F64_NEG : EPH_I32_TO_F64_POS);
}

#endif /* CASCADE_CONSTANTS_H */
