/* Auto-generated by tools/extract_stage_c.py — do not edit. */
#ifndef CASCADE_CONSTANTS_H
#define CASCADE_CONSTANTS_H

/* Verified stock scalars (current unpacked build) */
#define EPH_STOCK_WIDTH 640f
#define EPH_STOCK_HEIGHT 480f
#define EPH_ASPECT_4_3 1.33333337f
#define EPH_ONE 1f
#define EPH_HALF 2f
#define EPH_HUNDRED 100

/* Stage B aspect ladder (doubles @ prior Ghidra addresses) */
static const double kAspectBreakpoints[7] = {
    0.22500005352776498,  /* prior 0x53175EE8 */
    0.61111128306947649,  /* prior 0x53175F00 */
    1,  /* prior 0x53175F10 */
    1.01,  /* prior 0x53175F18 */
    1.3,  /* prior 0x53175F30 */
    1.3999999999999999,  /* prior 0x53175F40 */
    1.5  /* prior 0x53175F50 */
};

#endif /* CASCADE_CONSTANTS_H */
