/* Auto-generated by tools/extract_stage_c.py — do not edit. */
#ifndef STAGE_C_TABLES_H
#define STAGE_C_TABLES_H

#include <stdint.h>

/* kAnchorW: 122 slots @ prior 0x5318F040, rva 0x00DD1000 */
#define kAnchorW_COUNT 122
static const uint32_t kAnchorW[kAnchorW_COUNT] = {
    0x3A088889u,  /* dll/runtime — skip at apply */
    0x3F70A3D7u,  /* dll/runtime — skip at apply */
    0x00748A50u,  /* engine */
    0x0096E27Cu,  /* engine */
    0x004EC951u,  /* engine */
    0x00000006u,  /* dll/runtime — skip at apply */
    0x005D7BFCu,  /* engine */
    0x00000004u,  /* dll/runtime — skip at apply */
    0x00000000u,  /* dll/runtime — skip at apply */
    0x3FF00000u,  /* dll/runtime — skip at apply */
    0x00000000u,  /* dll/runtime — skip at apply */
    0x0000012Cu,  /* dll/runtime — skip at apply */
    0x3F800000u,  /* dll/runtime — skip at apply */
    0xFFFFFFA1u,  /* dll/runtime — skip at apply */
    0x3FE38E39u,  /* dll/runtime — skip at apply */
    0x3F800000u,  /* dll/runtime — skip at apply */
    0x00409F4Bu,  /* engine */
    0x0040A02Bu,  /* engine */
    0x0040A04Bu,  /* engine */
    0x0040C445u,  /* engine */
    0x0040C469u,  /* engine */
    0x0040C48Bu,  /* engine */
    0x00453809u,  /* engine */
    0x0045381Du,  /* engine */
    0x00483278u,  /* engine */
    0x004EB4AAu,  /* engine */
    0x004EB4F0u,  /* engine */
    0x004EC2D1u,  /* engine */
    0x004EF592u,  /* engine */
    0x004EF59Cu,  /* engine */
    0x00502D7Du,  /* engine */
    0x005BC90Eu,  /* engine */
    0x005BD783u,  /* engine */
    0x005BDB89u,  /* engine */
    0x007126ACu,  /* engine */
    0x00719AB1u,  /* engine */
    0x00719ACEu,  /* engine */
    0x00719C5Cu,  /* engine */
    0x00719C6Bu,  /* engine */
    0x00719D44u,  /* engine */
    0x00719D53u,  /* engine */
    0x00719E84u,  /* engine */
    0x0071A21Fu,  /* engine */
    0x00721E6Cu,  /* engine */
    0x00721E7Au,  /* engine */
    0x00721F2Au,  /* engine */
    0x00721FC0u,  /* engine */
    0x0077F2EDu,  /* engine */
    0x0077F30Du,  /* engine */
    0x0077F386u,  /* engine */
    0x0077F3A7u,  /* engine */
    0x00785641u,  /* engine */
    0x007856B1u,  /* engine */
    0x00785BD2u,  /* engine */
    0x007888A6u,  /* engine */
    0x007888C6u,  /* engine */
    0x00788EA6u,  /* engine */
    0x00788EC6u,  /* engine */
    0x00804EE0u,  /* engine */
    0x008051BAu,  /* engine */
    0x008F8EACu,  /* engine */
    0x008F8EBCu,  /* engine */
    0x008F8F50u,  /* engine */
    0x008F9A94u,  /* engine */
    0x008F9AA4u,  /* engine */
    0x008F9AC4u,  /* engine */
    0x008F9D38u,  /* engine */
    0x008F9D68u,  /* engine */
    0x008F9E8Cu,  /* engine */
    0x008F9EF8u,  /* engine */
    0x008F9F2Cu,  /* engine */
    0x008F9F34u,  /* engine */
    0x008F9F58u,  /* engine */
    0x008FA8A8u,  /* engine */
    0x008FAE50u,  /* engine */
    0x008FAE90u,  /* engine */
    0x008FFB84u,  /* engine */
    0x009007B8u,  /* engine */
    0x00909168u,  /* engine */
    0x00909D70u,  /* engine */
    0x00909D84u,  /* engine */
    0x00909DA8u,  /* engine */
    0x0091D8BCu,  /* engine */
    0x0091DA80u,  /* engine */
    0x0091E19Cu,  /* engine */
    0x0091FBF0u,  /* engine */
    0x0091FC54u,  /* engine */
    0x0091FC74u,  /* engine */
    0x0091FF94u,  /* engine */
    0x00920108u,  /* engine */
    0x00920164u,  /* engine */
    0x0092B6ECu,  /* engine */
    0x0092B71Cu,  /* engine */
    0x0092B740u,  /* engine */
    0x0092B780u,  /* engine */
    0x0096F5E0u,  /* engine */
    0x0096F694u,  /* engine */
    0x0096FE84u,  /* engine */
    0x0096FF60u,  /* engine */
    0x0096FF9Cu,  /* engine */
    0x0096FFC0u,  /* engine */
    0x009701F0u,  /* engine */
    0x00970640u,  /* engine */
    0x009706C0u,  /* engine */
    0x009707F8u,  /* engine */
    0x0097080Cu,  /* engine */
    0x009796F4u,  /* engine */
    0x00979A34u,  /* engine */
    0x00979A7Cu,  /* engine */
    0x00979A9Cu,  /* engine */
    0x00979DC4u,  /* engine */
    0x00979E00u,  /* engine */
    0x0097A170u,  /* engine */
    0x0097A1ACu,  /* engine */
    0x0097A1B8u,  /* engine */
    0x0097A6F4u,  /* engine */
    0x0097A740u,  /* engine */
    0x0097BB0Cu,  /* engine */
    0x0097BB58u,  /* engine */
    0x0097BBB0u,  /* engine */
    0x0097EBBCu,  /* engine */
    0x0097EC1Cu  /* engine */
};

/* kAnchorH: 90 slots @ prior 0x5318E6E0, rva 0x00DD06A0 */
#define kAnchorH_COUNT 90
static const uint32_t kAnchorH[kAnchorH_COUNT] = {
    0x00972578u,  /* engine */
    0x00972580u,  /* engine */
    0x00972620u,  /* engine */
    0x00972698u,  /* engine */
    0x00974E3Cu,  /* engine */
    0x00974E44u,  /* engine */
    0x009FF50Cu,  /* engine */
    0x008FADC8u,  /* engine */
    0x004137D0u,  /* engine */
    0x00972138u,  /* engine */
    0x0096FFFCu,  /* engine */
    0x009C94A0u,  /* engine */
    0x0091EEB8u,  /* engine */
    0x00972148u,  /* engine */
    0x00972120u,  /* engine */
    0x00000001u,  /* dll/runtime — skip at apply */
    0x0040A016u,  /* engine */
    0x0040A036u,  /* engine */
    0x00453827u,  /* engine */
    0x0045383Bu,  /* engine */
    0x004EB4B4u,  /* engine */
    0x004EB4FAu,  /* engine */
    0x004EC2E9u,  /* engine */
    0x00502D85u,  /* engine */
    0x007126A5u,  /* engine */
    0x00719AD9u,  /* engine */
    0x00719AF6u,  /* engine */
    0x00719C08u,  /* engine */
    0x00719C16u,  /* engine */
    0x00719C79u,  /* engine */
    0x00719C8Au,  /* engine */
    0x0071A226u,  /* engine */
    0x0077F3B2u,  /* engine */
    0x0077F3D2u,  /* engine */
    0x00785648u,  /* engine */
    0x00785680u,  /* engine */
    0x007856B8u,  /* engine */
    0x00785705u,  /* engine */
    0x00785BD9u,  /* engine */
    0x00785C11u,  /* engine */
    0x00785C49u,  /* engine */
    0x007888D1u,  /* engine */
    0x007888F1u,  /* engine */
    0x00788ED1u,  /* engine */
    0x00788EF1u,  /* engine */
    0x00804EF4u,  /* engine */
    0x008051CEu,  /* engine */
    0x008F9A98u,  /* engine */
    0x008F9AC8u,  /* engine */
    0x008FFB80u,  /* engine */
    0x00909164u,  /* engine */
    0x0091D8B8u,  /* engine */
    0x0091DA7Cu,  /* engine */
    0x0091FBECu,  /* engine */
    0x0091FC50u,  /* engine */
    0x0091FC70u,  /* engine */
    0x0091FF90u,  /* engine */
    0x00920050u,  /* engine */
    0x00920104u,  /* engine */
    0x00920160u,  /* engine */
    0x0096F5D8u,  /* engine */
    0x0096F698u,  /* engine */
    0x0096FF5Cu,  /* engine */
    0x0096FFA8u,  /* engine */
    0x0096FFBCu,  /* engine */
    0x009701ECu,  /* engine */
    0x00970648u,  /* engine */
    0x00970660u,  /* engine */
    0x009706C8u,  /* engine */
    0x009707F4u,  /* engine */
    0x00970808u,  /* engine */
    0x009796ECu,  /* engine */
    0x00979A28u,  /* engine */
    0x00979A70u,  /* engine */
    0x00979A8Cu,  /* engine */
    0x00979DC8u,  /* engine */
    0x00979DFCu,  /* engine */
    0x0097A16Cu,  /* engine */
    0x0097A1A8u,  /* engine */
    0x0097A1BCu,  /* engine */
    0x0097A6F0u,  /* engine */
    0x0097A73Cu,  /* engine */
    0x0097E9A8u,  /* engine */
    0x0097E9D8u,  /* engine */
    0x0097E9E4u,  /* engine */
    0x0097E9F0u,  /* engine */
    0x0097EA00u,  /* engine */
    0x0097EBB8u,  /* engine */
    0x0097EC18u,  /* engine */
    0x0097EC48u  /* engine */
};

/* kAnchorWaddHalf: 35 slots @ prior 0x5318E650, rva 0x00DD0610 */
#define kAnchorWaddHalf_COUNT 35
static const uint32_t kAnchorWaddHalf[kAnchorWaddHalf_COUNT] = {
    0xFF000000u,  /* dll/runtime — skip at apply */
    0x00FF0000u,  /* engine */
    0x00000001u,  /* dll/runtime — skip at apply */
    0xFFFF0033u,  /* dll/runtime — skip at apply */
    0xA0000000u,  /* dll/runtime — skip at apply */
    0x3FA99999u,  /* dll/runtime — skip at apply */
    0x00000001u,  /* dll/runtime — skip at apply */
    0x3DA3D70Au,  /* dll/runtime — skip at apply */
    0x79200278u,  /* dll/runtime — skip at apply */
    0x007103BCu,  /* engine */
    0x005D4D4Du,  /* engine */
    0x007489A6u,  /* engine */
    0x007489D0u,  /* engine */
    0x00748AECu,  /* engine */
    0x3ECCCCCDu,  /* dll/runtime — skip at apply */
    0x3D75C28Fu,  /* dll/runtime — skip at apply */
    0x0066DFEFu,  /* engine */
    0x00791C7Au,  /* engine */
    0x00792366u,  /* engine */
    0x00972000u,  /* engine */
    0x00972040u,  /* engine */
    0x00972048u,  /* engine */
    0x00972060u,  /* engine */
    0x009720A8u,  /* engine */
    0x009720E0u,  /* engine */
    0x009720E8u,  /* engine */
    0x009720F0u,  /* engine */
    0x009720F8u,  /* engine */
    0x00972100u,  /* engine */
    0x00972188u,  /* engine */
    0x00972508u,  /* engine */
    0x00972518u,  /* engine */
    0x00972530u,  /* engine */
    0x00972548u,  /* engine */
    0x00972550u  /* engine */
};

/* kAnchorWaddFull: 28 slots @ prior 0x5318F2A0, rva 0x00DD1260 */
#define kAnchorWaddFull_COUNT 28
static const uint32_t kAnchorWaddFull[kAnchorWaddFull_COUNT] = {
    0x007103C5u,  /* engine */
    0x009006F8u,  /* engine */
    0x00900700u,  /* engine */
    0x00900708u,  /* engine */
    0x00900710u,  /* engine */
    0x00900718u,  /* engine */
    0x00900720u,  /* engine */
    0x00000001u,  /* dll/runtime — skip at apply */
    0x00748997u,  /* engine */
    0x00000003u,  /* dll/runtime — skip at apply */
    0x005D2BFFu,  /* engine */
    0x41400000u,  /* dll/runtime — skip at apply */
    0x3E99999Au,  /* dll/runtime — skip at apply */
    0x3F800000u,  /* dll/runtime — skip at apply */
    0x007103C0u,  /* engine */
    0x7920062Cu,  /* dll/runtime — skip at apply */
    0x00783A92u,  /* engine */
    0x00972010u,  /* engine */
    0x00972050u,  /* engine */
    0x00972058u,  /* engine */
    0x00972540u,  /* engine */
    0x009720B0u,  /* engine */
    0x009720B8u,  /* engine */
    0x00972078u,  /* engine */
    0x009725E8u,  /* engine */
    0x009725D0u,  /* engine */
    0x00972610u,  /* engine */
    0x00A11324u  /* engine */
};

/* kAnchorHaddFull: 235 slots @ prior 0x5318E9C8, rva 0x00DD0988 */
#define kAnchorHaddFull_COUNT 235
static const uint32_t kAnchorHaddFull[kAnchorHaddFull_COUNT] = {
    0x00A11324u,  /* engine */
    0x00A11328u,  /* engine */
    0x00A1132Cu,  /* engine */
    0x00A11330u,  /* engine */
    0x00A113E8u,  /* engine */
    0x00A113ECu,  /* engine */
    0x00A11400u,  /* engine */
    0x00A11404u,  /* engine */
    0x00A11390u,  /* engine */
    0x00A11394u,  /* engine */
    0x00A11398u,  /* engine */
    0x00A1139Cu,  /* engine */
    0x00A11418u,  /* engine */
    0x3DCCCCCDu,  /* dll/runtime — skip at apply */
    0x006A114Fu,  /* engine */
    0x3ECCCCCDu,  /* dll/runtime — skip at apply */
    0x006F4D9Fu,  /* engine */
    0x006FFCB8u,  /* engine */
    0x006FFCE0u,  /* engine */
    0x006FFCF4u,  /* engine */
    0x006FFD12u,  /* engine */
    0x006FFD1Cu,  /* engine */
    0x006FFD58u,  /* engine */
    0x006FFD76u,  /* engine */
    0x0070D2CEu,  /* engine */
    0x0070D2ECu,  /* engine */
    0x0070D30Au,  /* engine */
    0x0070D328u,  /* engine */
    0x0070D346u,  /* engine */
    0x0070D364u,  /* engine */
    0x0070D382u,  /* engine */
    0x0070D3A0u,  /* engine */
    0x0070D3B4u,  /* engine */
    0x0070D3D2u,  /* engine */
    0x0070D3F0u,  /* engine */
    0x0070D404u,  /* engine */
    0x00407F9Du,  /* engine */
    0x00403114u,  /* engine */
    0x0071A8F8u,  /* engine */
    0x0071A905u,  /* engine */
    0x0071A988u,  /* engine */
    0x0071A995u,  /* engine */
    0x007403F6u,  /* engine */
    0x0074467Du,  /* engine */
    0x0074468Du,  /* engine */
    0x007446D8u,  /* engine */
    0x007446E8u,  /* engine */
    0x00744723u,  /* engine */
    0x00744733u,  /* engine */
    0x0074477Eu,  /* engine */
    0x0074478Eu,  /* engine */
    0x007583C8u,  /* engine */
    0x007583E3u,  /* engine */
    0x007583FEu,  /* engine */
    0x00758412u,  /* engine */
    0x007584F5u,  /* engine */
    0x0075850Fu,  /* engine */
    0x00758526u,  /* engine */
    0x0075853Fu,  /* engine */
    0x00761CC7u,  /* engine */
    0x00761CD9u,  /* engine */
    0x00762367u,  /* engine */
    0x00762602u,  /* engine */
    0x007627DFu,  /* engine */
    0x00783AAAu,  /* engine */
    0x008F87D8u,  /* engine */
    0x008F87E0u,  /* engine */
    0x0096E534u,  /* engine */
    0x0096E53Cu,  /* engine */
    0x0096E54Cu,  /* engine */
    0x0096E574u,  /* engine */
    0x0096E5FCu,  /* engine */
    0x0096E660u,  /* engine */
    0x0096FC44u,  /* engine */
    0x0096FC54u,  /* engine */
    0x0097061Cu,  /* engine */
    0x00970638u,  /* engine */
    0x0097066Cu,  /* engine */
    0x009710BCu,  /* engine */
    0x00971F44u,  /* engine */
    0x00971F4Cu,  /* engine */
    0x00971F54u,  /* engine */
    0x00971F5Cu,  /* engine */
    0x00971F64u,  /* engine */
    0x00971F6Cu,  /* engine */
    0x00971F74u,  /* engine */
    0x00971F7Cu,  /* engine */
    0x00971F84u,  /* engine */
    0x00971F8Cu,  /* engine */
    0x00971F94u,  /* engine */
    0x00971F9Cu,  /* engine */
    0x00971FA4u,  /* engine */
    0x00971FACu,  /* engine */
    0x00971FBCu,  /* engine */
    0x00971FC4u,  /* engine */
    0x00971FCCu,  /* engine */
    0x00971FD4u,  /* engine */
    0x00971FDCu,  /* engine */
    0x00971FE4u,  /* engine */
    0x00971FECu,  /* engine */
    0x00971FF4u,  /* engine */
    0x00971FFCu,  /* engine */
    0x00972004u,  /* engine */
    0x0097200Cu,  /* engine */
    0x00972014u,  /* engine */
    0x00972024u,  /* engine */
    0x0097206Cu,  /* engine */
    0x00972094u,  /* engine */
    0x0097209Cu,  /* engine */
    0x009720A4u,  /* engine */
    0x009720B4u,  /* engine */
    0x009720CCu,  /* engine */
    0x009720FCu,  /* engine */
    0x0097214Cu,  /* engine */
    0x00972224u,  /* engine */
    0x0097222Cu,  /* engine */
    0x00972234u,  /* engine */
    0x0097223Cu,  /* engine */
    0x00972244u,  /* engine */
    0x0097224Cu,  /* engine */
    0x00972254u,  /* engine */
    0x0097225Cu,  /* engine */
    0x00972264u,  /* engine */
    0x0097227Cu,  /* engine */
    0x00972284u,  /* engine */
    0x009722DCu,  /* engine */
    0x009722E4u,  /* engine */
    0x009722ECu,  /* engine */
    0x009722F4u,  /* engine */
    0x009722FCu,  /* engine */
    0x00972304u,  /* engine */
    0x0097230Cu,  /* engine */
    0x00972314u,  /* engine */
    0x0097231Cu,  /* engine */
    0x00972324u,  /* engine */
    0x0097232Cu,  /* engine */
    0x00972334u,  /* engine */
    0x0097233Cu,  /* engine */
    0x00972344u,  /* engine */
    0x0097234Cu,  /* engine */
    0x00972354u,  /* engine */
    0x0097235Cu,  /* engine */
    0x00972364u,  /* engine */
    0x0097236Cu,  /* engine */
    0x00972374u,  /* engine */
    0x0097237Cu,  /* engine */
    0x00972384u,  /* engine */
    0x0097238Cu,  /* engine */
    0x00972394u,  /* engine */
    0x0097239Cu,  /* engine */
    0x009723A4u,  /* engine */
    0x009723ACu,  /* engine */
    0x009723B4u,  /* engine */
    0x009723BCu,  /* engine */
    0x009723C4u,  /* engine */
    0x009723CCu,  /* engine */
    0x009723D4u,  /* engine */
    0x009723DCu,  /* engine */
    0x009723E4u,  /* engine */
    0x009723ECu,  /* engine */
    0x009723F4u,  /* engine */
    0x009723FCu,  /* engine */
    0x00972404u,  /* engine */
    0x0097240Cu,  /* engine */
    0x00972414u,  /* engine */
    0x0097241Cu,  /* engine */
    0x00972424u,  /* engine */
    0x0097242Cu,  /* engine */
    0x00972434u,  /* engine */
    0x0097243Cu,  /* engine */
    0x00972444u,  /* engine */
    0x0097244Cu,  /* engine */
    0x00972454u,  /* engine */
    0x0097245Cu,  /* engine */
    0x00972464u,  /* engine */
    0x0097246Cu,  /* engine */
    0x00972474u,  /* engine */
    0x0097247Cu,  /* engine */
    0x00972484u,  /* engine */
    0x0097248Cu,  /* engine */
    0x00972494u,  /* engine */
    0x0097249Cu,  /* engine */
    0x009724A4u,  /* engine */
    0x009724ACu,  /* engine */
    0x009724B4u,  /* engine */
    0x009724BCu,  /* engine */
    0x009724C4u,  /* engine */
    0x009724CCu,  /* engine */
    0x009724D4u,  /* engine */
    0x009724DCu,  /* engine */
    0x009724E4u,  /* engine */
    0x009724ECu,  /* engine */
    0x009724F4u,  /* engine */
    0x009724FCu,  /* engine */
    0x00972504u,  /* engine */
    0x00972554u,  /* engine */
    0x0097255Cu,  /* engine */
    0x00972564u,  /* engine */
    0x0097256Cu,  /* engine */
    0x0097258Cu,  /* engine */
    0x00972594u,  /* engine */
    0x0097259Cu,  /* engine */
    0x009725A4u,  /* engine */
    0x009725ACu,  /* engine */
    0x009725B4u,  /* engine */
    0x009725BCu,  /* engine */
    0x009725C4u,  /* engine */
    0x009725CCu,  /* engine */
    0x009725D4u,  /* engine */
    0x009725E4u,  /* engine */
    0x009725ECu,  /* engine */
    0x00972614u,  /* engine */
    0x0097261Cu,  /* engine */
    0x00972700u,  /* engine */
    0x00974E40u,  /* engine */
    0x00974E48u,  /* engine */
    0x009D0044u,  /* engine */
    0x009FF084u,  /* engine */
    0x009FF09Cu,  /* engine */
    0x009FF0B4u,  /* engine */
    0x009FF0CCu,  /* engine */
    0x009FF0E4u,  /* engine */
    0x009FF0FCu,  /* engine */
    0x009FF114u,  /* engine */
    0x009FF12Cu,  /* engine */
    0x009FF1ACu,  /* engine */
    0x00A1133Cu,  /* engine */
    0x00A113A4u,  /* engine */
    0x00A113ACu,  /* engine */
    0x00A113F4u,  /* engine */
    0x0070D4F4u,  /* engine */
    0x0070D508u,  /* engine */
    0x0070D4E0u,  /* engine */
    0x0070D4D6u,  /* engine */
    0x0070D422u  /* engine */
};

/* kAnchorHaddHalf: 12 slots @ prior 0x5318EF00, rva 0x00DD0EC0 */
#define kAnchorHaddHalf_COUNT 12
static const uint32_t kAnchorHaddHalf[kAnchorHaddHalf_COUNT] = {
    0x792005C4u,  /* dll/runtime — skip at apply */
    0x792005D0u,  /* dll/runtime — skip at apply */
    0x792005E0u,  /* dll/runtime — skip at apply */
    0x79200600u,  /* dll/runtime — skip at apply */
    0x7920060Cu,  /* dll/runtime — skip at apply */
    0x00000000u,  /* dll/runtime — skip at apply */
    0x005B92DEu,  /* engine */
    0x009006F4u,  /* engine */
    0x009006FCu,  /* engine */
    0x00900704u,  /* engine */
    0x0090070Cu,  /* engine */
    0x00900714u  /* engine */
};

/* kAspectMultPtr: 12 slots @ prior 0x5318EE3C, rva 0x00DD0DFC */
#define kAspectMultPtr_COUNT 12
static const uint32_t kAspectMultPtr[kAspectMultPtr_COUNT] = {
    0x0047ECB4u,  /* engine */
    0x000000DCu,  /* dll/runtime — skip at apply */
    0x0047ECB4u,  /* engine */
    0x000000EBu,  /* dll/runtime — skip at apply */
    0x0047ECCCu,  /* engine */
    0x0000001Du,  /* dll/runtime — skip at apply */
    0x0047BA0Cu,  /* engine */
    0x000000EFu,  /* dll/runtime — skip at apply */
    0x007C94FCu,  /* engine */
    0x00000022u,  /* dll/runtime — skip at apply */
    0x007F2E5Cu,  /* engine */
    0x00000012u  /* dll/runtime — skip at apply */
};

/* kScaleW: 2 slots @ prior 0x5318F00C, rva 0x00DD0FCC */
#define kScaleW_COUNT 2
static const uint32_t kScaleW[kScaleW_COUNT] = {
    0x3FD00000u,  /* dll/runtime — skip at apply */
    0x00000000u  /* dll/runtime — skip at apply */
};

/* kScaleH: 20 slots @ prior 0x5318EF40, rva 0x00DD0F00 */
#define kScaleH_COUNT 20
static const uint32_t kScaleH[kScaleH_COUNT] = {
    0x00972054u,  /* engine */
    0x0097205Cu,  /* engine */
    0x009720E4u,  /* engine */
    0x009720ECu,  /* engine */
    0x00972104u,  /* engine */
    0x009720F4u,  /* engine */
    0x0066DFFAu,  /* engine */
    0x0097213Cu,  /* engine */
    0x0096FFF4u,  /* engine */
    0x009C94A4u,  /* engine */
    0x0091EEB4u,  /* engine */
    0x00972124u,  /* engine */
    0x0080030Cu,  /* engine */
    0x0083AE16u,  /* engine */
    0x00000000u,  /* dll/runtime — skip at apply */
    0x00748A57u,  /* engine */
    0x0096E278u,  /* engine */
    0x0091DC0Cu,  /* engine */
    0x0091DC04u,  /* engine */
    0x0091DBFCu  /* engine */
};

/* kUshortH: 12 slots @ prior 0x5318E8FC, rva 0x00DD08BC */
#define kUshortH_COUNT 12
static const uint32_t kUshortH[kUshortH_COUNT] = {
    0x79200458u,  /* dll/runtime — skip at apply */
    0x79200464u,  /* dll/runtime — skip at apply */
    0x79200470u,  /* dll/runtime — skip at apply */
    0x009BE1E8u,  /* engine */
    0x3F19999Au,  /* dll/runtime — skip at apply */
    0x00000001u,  /* dll/runtime — skip at apply */
    0x00937950u,  /* engine */
    0x00938E34u,  /* engine */
    0x0093B270u,  /* engine */
    0x0093B330u,  /* engine */
    0x00927318u,  /* engine */
    0x00709F67u  /* engine */
};

/* kPlayerScale: 5 slots @ prior 0x5318E8D4, rva 0x00DD0894 */
#define kPlayerScale_COUNT 5
static const uint32_t kPlayerScale[kPlayerScale_COUNT] = {
    0x792003D4u,  /* dll/runtime — skip at apply */
    0x792003E0u,  /* dll/runtime — skip at apply */
    0x792003ECu,  /* dll/runtime — skip at apply */
    0x792003F8u,  /* dll/runtime — skip at apply */
    0x79200408u  /* dll/runtime — skip at apply */
};

#endif /* STAGE_C_TABLES_H */
